[tool.poetry]
name = "postcactus"
version = "3.0.0a3"
description = "Read and process Einstein Toolkit simulations."
authors = ["Gabriele Bozzola <gabrielebozzola@arizona.edu>"]
maintainers = ["Gabriele Bozzola <gabrielebozzola@arizona.edu>"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://github.com/sbozzolo/PostCactus"
repository = "https://github.com/sbozzolo/PostCactus"
documentation = "https://sbozzolo.github.io/PostCactus"
include = [
        "logo.png",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/sbozzolo/PostCactus/issues"

[tool.poetry.dependencies]
python = "^3.5"
numpy = "^1.18.5"
scipy = "^1.4.0"
h5py = "^2.10.0"
numba = "^0.47.0"

[tool.poetry.dev-dependencies]
lalsuite = "^6.76"
black = {version = "^20.8b1", python = "^3.6"}
coverage = "^5.3"
pycbc = "^1.16.9"
Sphinx = "^3.2.1"
nbsphinx = "^0.7.1"
jupyter = "^1.0.0"

[tool.black]
line-length = 79
exclude = '''
/(
    \.git
  | \.hg
  | docs
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

