[tool.poetry]
name = "postcactus"
version = "3.0.0a3"
description = "Read and process Einstein Toolkit simulations."
authors = ["Gabriele Bozzola <gabrielebozzola@arizona.edu>"]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "*"
scipy = "*"
h5py = "^2.10.0"
numba = "^0.51.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
lalsuite = "^6.76"
black = "^20.8b1"
coverage = "^5.3"
pycbc = "^1.16.9"
Sphinx = "^3.2.1"
nbsphinx = "^0.7.1"

[tool.black]
line-length = 79
exclude = '''
/(
    \.git
  | \.hg
  | docs
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

